#!/usr/bin/env bash

Top=$(git rev-parse --show-toplevel)
worker() {
gawk 'BEGIN {  
         q="\""
         print ""
         First = 1      
         In = 1
  }         
  /^"""</,/^>"""/ {  next } 
  /^"""/          {  In = 1 - In       
                     if (In)            
                       print "````python"
                     else          
                       if (First)   
                         First = 0   
                       else     
                         print "````"  
                     next }       
  ! First { print $0 }       
  END     { if (In) print "````"  }'
} 

main() {
  arg=$1
  file=$(basename $arg)
  stem="${file%%.*}"
  out=$Top/docs/${stem}.md
  if [ "$arg" -nt "$out" ]; then
    echo "# $(basename $arg) ==> docs/$stem.out"
    (
    cat  $Top/etc/header.md $Top/etc/toc.md
    cat $1 | worker  
    cat $Top/etc/footer.md 
    ) > $out
  fi
  
  git add $Top/docs/${stem}.md
  
}

if [ -n "$1" ]; then
  main $1
else
  for f in $Top/src/*.py; do
    main $f
  done
fi
git commit -am as

