#!/usr/bin/env bash

worker() {
gawk 'BEGIN {  
         q="\""
         print ""
         First = 1      
         In = 1
  }         
  /^"""</,/^>"""/ {  next } 
  /^"""/          {  In = 1 - In       
                     if (In)            
                       print "````python"
                     else          
                       if (First)   
                         First = 0   
                       else     
                         print "````"  
                     next }       
  ! First { print $0 }       
  END     { if (In) print "````"  }'
} 


stem="${1%%.*}"

(
cat  ../etc/header.md ../etc/toc.md
cat $1 | worker  
cat ../etc/footer.md 
) > ../docs/${stem}.md

git add ../docs/${stem}.md
git commit -am as

